require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ShipsController do

  def mock_ship(stubs={})
    @mock_ship ||= mock_model(Ship, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ships as @ships" do
      Ship.stub(:all) { [mock_ship] }
      get :index
      assigns(:ships).should eq([mock_ship])
    end
  end

  describe "GET show" do
    it "assigns the requested ship as @ship" do
      Ship.stub(:find).with("37") { mock_ship }
      get :show, :id => "37"
      assigns(:ship).should be(mock_ship)
    end
  end

  describe "GET new" do
    it "assigns a new ship as @ship" do
      Ship.stub(:new) { mock_ship }
      get :new
      assigns(:ship).should be(mock_ship)
    end
  end

  describe "GET edit" do
    it "assigns the requested ship as @ship" do
      Ship.stub(:find).with("37") { mock_ship }
      get :edit, :id => "37"
      assigns(:ship).should be(mock_ship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ship as @ship" do
        Ship.stub(:new).with({'these' => 'params'}) { mock_ship(:save => true) }
        post :create, :ship => {'these' => 'params'}
        assigns(:ship).should be(mock_ship)
      end

      it "redirects to the created ship" do
        Ship.stub(:new) { mock_ship(:save => true) }
        post :create, :ship => {}
        response.should redirect_to(ship_url(mock_ship))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ship as @ship" do
        Ship.stub(:new).with({'these' => 'params'}) { mock_ship(:save => false) }
        post :create, :ship => {'these' => 'params'}
        assigns(:ship).should be(mock_ship)
      end

      it "re-renders the 'new' template" do
        Ship.stub(:new) { mock_ship(:save => false) }
        post :create, :ship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ship" do
        Ship.stub(:find).with("37") { mock_ship }
        mock_ship.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ship => {'these' => 'params'}
      end

      it "assigns the requested ship as @ship" do
        Ship.stub(:find) { mock_ship(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ship).should be(mock_ship)
      end

      it "redirects to the ship" do
        Ship.stub(:find) { mock_ship(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ship_url(mock_ship))
      end
    end

    describe "with invalid params" do
      it "assigns the ship as @ship" do
        Ship.stub(:find) { mock_ship(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ship).should be(mock_ship)
      end

      it "re-renders the 'edit' template" do
        Ship.stub(:find) { mock_ship(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ship" do
      Ship.stub(:find).with("37") { mock_ship }
      mock_ship.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ships list" do
      Ship.stub(:find) { mock_ship }
      delete :destroy, :id => "1"
      response.should redirect_to(ships_url)
    end
  end

end
